# Generated by Django 5.0.6 on 2025-03-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0002_remove_logo_and_custom_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='client',
            field=models.ForeignKey(blank=True, help_text='The CRM client associated with this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='ecomm_superadmin.crmclient'),
        ),
    ]
